name: Debian / Ubuntu latest 7.4 build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  php-7_4:

    runs-on: ubuntu-latest

    container: ${{ matrix.container }}

    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/GMT

    strategy:
      matrix:
        container: ["debian:bullseye", "ubuntu:focal"]
        php-version: [7.4]

    steps:
    - uses: actions/checkout@v3

    - name: Set timezone
      run: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    - name: Apt update ${{ matrix.container }}
      run: apt update && apt upgrade -y
    - name: Install php${{ matrix.php-version }}-dev on ${{ matrix.container }}
      run: apt install -y php${{ matrix.php-version }}-dev
    - name: Run PHPize on source on ${{ matrix.container }}
      run: /usr/bin/phpize${{ matrix.php-version }}
    - name: Configure source on ${{ matrix.container }}
      run: ./configure
    - name: Make source on ${{ matrix.container }}
      run: make

  php-8_1:

    runs-on: ubuntu-latest

    container: ${{ matrix.container }}

    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/GMT

    strategy:
      matrix:
        container: ["debian:sid", "ubuntu:22.04"]
        php-version: [8.1]

    steps:
    - uses: actions/checkout@v3

    - name: Set timezone
      run: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    - name: Apt update ${{ matrix.container }}
      run: apt update && apt upgrade -y
    - name: Install php${{ matrix.php-version }}-dev on ${{ matrix.container }}
      run: apt install -y php${{ matrix.php-version }}-dev
    - name: Run PHPize on source on ${{ matrix.container }}
      run: /usr/bin/phpize${{ matrix.php-version }}
    - name: Configure source on ${{ matrix.container }}
      run: ./configure
    - name: Make source on ${{ matrix.container }}
      run: make
